name: Scrape Return Notes
on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup workspace
        run: mkdir -p workspace

      - name: Create files manually
        working-directory: workspace
        run: |
          # Initialize database
          sqlite3 return_notes.db "CREATE TABLE IF NOT EXISTS parcels (
            id INTEGER PRIMARY KEY,
            data TEXT
          );"

          # Create log file
          echo "INITIALIZED $(date)" > scraper.log
          ls -lah

      - name: Run scraper
        working-directory: workspace
        run: |
          node ../scraper.js 2>&1 | tee -a scraper.log

      - name: Verify output
        run: |
          sqlite3 workspace/return_notes.db ".tables"
          sqlite3 workspace/return_notes.db "SELECT COUNT(*) FROM parcels;"
          tail -n 10 workspace/scraper.log

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: scraping-data
          path: |
            workspace/return_notes.db
            workspace/scraper.log
