name: Puppeteer Automation

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run-puppeteer:
    runs-on: windows-latest # Windows runner
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Puppeteer
        run: node puppeteer-script.js

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshots/example.png

      - name: Verify JSON output
        run: |
          echo "Generated file contents:"
          dir data\
          type data\return-notes.json | jq '. | length' || echo "No JSON file found"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/return-notes.json
          git status
          git commit -m "Update return notes data [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"
