name: Run Return Notes Scraper

on:
  schedule:
    - cron: "0 8 * * *" # Runs daily at 8 AM UTC
  workflow_dispatch:

env:
  CI: true
  LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
  LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install puppeteer sqlite3

      - name: Create data directory
        run: mkdir -p .github/private

      - name: Run scraper
        id: run-scraper
        run: |
          node scraper.js || echo "::error::Scraper failed"
          echo "scraper_exit_code=$?" >> $GITHUB_OUTPUT

      - name: Output error details
        if: steps.run-scraper.outputs.scraper_exit_code != '0'
        run: |
          echo "Scraper failed with exit code ${{ steps.run-scraper.outputs.scraper_exit_code }}"
          [ -f ".github/private/error.json" ] && cat ".github/private/error.json" || echo "No error details available"

      - name: Commit and push changes
        if: steps.run-scraper.outputs.scraper_exit_code == '0'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update return notes data" || echo "No changes to commit"
          git push || echo "No changes to push"
